// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manuscriptSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: '📘 行为模拟论总览',
    },
    {
      type: 'category',
      label: 'Front Matter 前置导引',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'front-matter'}],
    },
    {
      type: 'category',
      label: 'Part 01 · Conceptual Field 概念场域',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-01-conceptual'}],
    },
    {
      type: 'category',
      label: 'Part 02 · Foundations 方法论根基',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-02-foundations'}],
    },
    {
      type: 'category',
      label: 'Part 03 · Methods 设计作业',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-03-methods'}],
    },
    {
      type: 'category',
      label: 'Part 04 · Integration 体系整合',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-04-integration'}],
    },
    {
      type: 'category',
      label: 'Part 05 · Applications 场景应用',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-05-applications'}],
    },
    {
      type: 'category',
      label: 'Part 06 · Futures & Governance 前瞻治理',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-06-futures-governance'}],
    },
    {
      type: 'category',
      label: 'Back Matter 附录与索引',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'back-matter'}],
    },
  ],
};

module.exports = sidebars;
