// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manuscriptSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: '📘 行为模拟论总览',
    },
    {
      type: 'category',
      label: '前置导引',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'front-matter'}],
    },
    {
      type: 'category',
      label: '第一部分｜认识框架',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-01-conceptual'}],
    },
    {
      type: 'category',
      label: '第二部分｜理论基础与发展动因',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-02-foundations'}],
    },
    {
      type: 'category',
      label: '第三部分｜方法体系与操作框架',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-03-methods'}],
    },
    {
      type: 'category',
      label: '第四部分｜范式对比与协同机制',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-04-integration'}],
    },
    {
      type: 'category',
      label: '第五部分｜应用案例与实践指南',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-05-applications'}],
    },
    {
      type: 'category',
      label: '第六部分｜未来展望与治理框架',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'parts/part-06-futures-governance'}],
    },
    {
      type: 'category',
      label: 'Back Matter 附录与索引',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'back-matter'}],
    },
  ],
};

module.exports = sidebars;
